[package]
name = "htp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy-table = "5.0.1"
futures = "0.3.21"
humantime = "2.1.0"
hyper = { version = "0.14.17", features = ["client", "http2", "http1"] }
hyper-tls = "0.5.0"
lazy_static = "1.4.0"
rayon = "1.5.1"
reqwest = { version = "0.11.9", features = ["blocking"] }
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
